# Select image from https://hub.docker.com/iamapinan/php-nginx-mongo
image: iamapinan/php-nginx-mongo:1.3

stages:
   - test
   - deploy

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
  - composer install
  - pecl install xdebug && docker-php-ext-enable xdebug

test:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-html --colors=auto

deploy:
  stage: deploy
  environment: production
  script:
    - ls
    - ssh $DEPLOY_HOST_USER@$DEPLOY_HOST_B