# Select image from https://hub.docker.com/iamapinan/php-nginx-mongo
image: php:7.1

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/

build:
  stage: build
  only:
    - master
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

test:
  stage: test
  only:
    - master
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --colors=auto

deploy:
  stage: deploy
  only:
    - master
  environment: production
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIV_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_HOST_B >> ~/.ssh/known_hosts
    - ssh root@$DEPLOY_HOST_B