# Select image from https://hub.docker.com/iamapinan/php-nginx-mongo
image: iamapinan/php-nginx-mongo:1.3

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - vendor/
  only:
    - master
  script:
    - apk add openssh
    - composer install
    - vendor/bin/phpunit --configuration phpunit.xml --colors=auto

deploy:
  stage: deploy
  only:
    - master
  environment: production
  script:
    - ls
    - >
      ssh root@$DEPLOY_HOST_B