version: '3'

services:
  app:
    image: iamapinan/ioframework:v1
    ports:
      - 9000
    volumes:
      - ./:/var/www
    
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      